apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-annotate-webhook
  labels:
    app: pod-annotate-webhook
    kind: mutator
webhooks:
  - name: pod-annotate-webhook.slok.xyz
    clientConfig:
      service:
        name: pod-annotate-webhook
        namespace: vault
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6akNDQWJZQ0NRRDM5Tm1peUNpendUQU5CZ2txaGtpRzl3MEJBUXNGQURBcE1TY3dKUVlEVlFRRERCNXcKYjJRdFlXNXViM1JoZEdVdGQyVmlhRzl2YXk1MllYVnNkQzV6ZG1Nd0hoY05NVGt4TVRBMU1EVXdOREEwV2hjTgpNakF4TVRBME1EVXdOREEwV2pBcE1TY3dKUVlEVlFRRERCNXdiMlF0WVc1dWIzUmhkR1V0ZDJWaWFHOXZheTUyCllYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNxRDVIQ2txVGcKRjV0Y3NFOUY1Q0JaSVcrNGxCSjVjS0xyVG5oNHlHM0tmMEFvN1huOUR2ODlESFFWZHpJOTEyd1E5VytGdUU5NQpPY3U5bzd3VEhOSEdFbGt6bzZhQzNGMXB6L1R6TXZKcTBTSmpEL0UrZzdsKzlsei81LzFOZWJiL3dLVkE1cW4xCnBxdVExTjRIRXNNRjRocXNhbWFtTFVLZFNMcHljL2xUeDRTMktYcXVqdUNEUk9wbUx3REFFQXQ1cDNjMnRrSmgKZHNUQkw0NGFFRmVhdlF0UTlsNy96U0w3OGJoY2k0T1dYdVJCSUF2Z2VnQU1sSVcxWjhWNUk1T0N1dTJTV0c3RwpKOFRlTzdISGpXc0NGZlpLS1I3L1JxWkhVUm9CMks4a2F2MDBWOWJLVHpFSnBVbCtHdTdxRS8zZXhFTDBWWWZZCmx2TWFEZ1g4RlEzSEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFkRjJjSUhoVzFGNGRlK3VYNHEKQ2kzeFNDM0w3elIyZENVbDFqajE4UnRkc1lmNlFYVEFNaitvVTF3UWxNb0FEZ3plbitnYUt0SXdqc1NQeE12VApOOEl2cG81NEpxZXJQYVlVbWtnMHJvZXFSdzUzZkJGLy9GM3lTMEtNVGdZK2xEU2pSU0hxTzl2U3B0dmlhbWFWCjZZdjNqek9EMmttOE9UYXNWajdnNlM2UGZZWWVVaHYvVnUwUjBFcUFRdVpHN0VkTGhObU9Xa2hwVFBYU0RKOVYKb2JlbWJaMzRHSHpJa3NOcVR4c2N3Njh4azM5dGV5QWNCMkVpbk9OS1JFM1JBR2NpVHdKOGl6UWRlSGttV0djWAp2RGdBd1lnY25uRUVaR1d5V1RwZU01Ky9wOWFzQmxXTUlIRE1US1laSUk3VkpPSnVPcHVTdmEvUlFUZUxmY2RnCjhzcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]

